
AUTH_SERVER_TOGGLE: false # ENABLE ONLY IF YOU ARE USING A SERVER WITH AUTH SYSTEM.

DELETE_PLAYER_CACHE_TIME: 15

KICK_PLAYER_TIME: 45

# THIS OPTIONS NEED "AUTH_SERVER_TOGGLE" TOGGLED TRUE.

LOBBY-SERVER:
  SERVER:
    - 'lobby'

AUTH-SERVER:
  SERVER:
    - 'auth'